-- 01
SELECT * FROM PESSOA p
RIGHT JOIN CONTATO c	
ON p.ID_PESSOA = c.ID_PESSOA

-- 02
SELECT P.ID_PESSOA, PXPE.ID_PESSOA, pxpe.ID_ENDERECO, ep.ID_ENDERECO  FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON p.ID_PESSOA = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep 
ON PXPE.ID_ENDERECO = ep.ID_ENDERECO

-- 03
SELECT * FROM PESSOA p
RIGHT JOIN CONTATO c	
ON p.ID_PESSOA = c.ID_PESSOA
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON p.ID_PESSOA = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep 
ON PXPE.ID_ENDERECO = ep.ID_ENDERECO

-- 04
SELECT * FROM PESSOA p
FULL JOIN CONTATO c	
ON p.ID_PESSOA = c.ID_PESSOA

-- 05
SELECT *  FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep 
ON PXPE.ID_ENDERECO = ep.ID_ENDERECO

-- 06
SELECT * FROM PESSOA p
FULL JOIN CONTATO c	
ON p.ID_PESSOA = c.ID_PESSOA
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON c.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep 
ON PXPE.ID_ENDERECO = ep.ID_ENDERECO

-- 07
SELECT p.ID_PESSOA, nome FROM PESSOA p 
WHERE EXISTS (SELECT ID_PESSOA FROM ENDERECO_PESSOA ep JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON PXPE.ID_ENDERECO = ep.ID_ENDERECO)

-- 08
SELECT P.ID_PESSOA, p.nome, ep.ID_ENDERECO, ep.LOGRADOURO FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep 
ON PXPE.ID_ENDERECO = ep.ID_ENDERECO
